version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/family-tree
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      # local test env vars
      - HEROKU_POSTGRESQL_SILVER_URL=postgresql://postgres@db:5432/family-tree_test
  webpacker:
    image: family-tree_web
    command: ["./webpack_dev.sh"]
    volumes:
      - .:/family-tree:cached
    ports:
      - 3035:3035
    depends_on:
      - db
      - web
