default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: family-tree_development
  host: db
  username: postgres
  password:

test:
  <<: *default
  url: <%= ENV['HEROKU_POSTGRESQL_SILVER_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
