name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Define variables
      run: |
        echo "registry.heroku.com/pepler-family-tree/web" > TAG
    - name: eslint
      run: npm run lint
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $(cat TAG)
    - name: Heroku Release
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        docker push $(cat TAG)
        heroku container:release web --app $HEROKU_APP_NAME
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
